### ISSUE TITLE
Overkiz RTS Shutters

### ISSUE THREAD

**Issue by luckyzor** [duhow/hass-cover-time-based#3]
Hello,

Im searching for a way to set positioning of my dumb RTS shutters.
Overkiz + tahomav2 + rts shutter:
RTS Shutter have 4 buttons in HA: "open" / "stop" / "close" / "favorite position"
Do you think I can use this integration for my use case?
I want to know if the shutter is closed/opened or in the "favorite position" and using time, the % position.

Thank you in advance

**Comment by duhow** [comment]
Assuming that "favorite position" turns up/down to a specific position (by turning on the relevant switches), the rest should work.

**Comment by luckyzor** [comment]
> Assuming that "favorite position" turns up/down to a specific position (by turning on the relevant switches), the rest should work.

It works, but the status of the covers are always "unknown". So I don't know if they are closed, open or in the favorite position.

**Comment by duhow** [comment]
That is because either the Up or Down switch is unavailable, and so it turns the whole cover as unavailable. This can happen if Zigbee switches are disconnected, for example.

**Comment by luckyzor** [comment]
I never talked about ZigBee switchs, I don't have any.
My question was to virtually create the open/close and favourite position as state of the cover, instead of having it as unknown

**Comment by duhow** [comment]
If you have any entity (kind `switch`, `light`, or any other supported) in Home Assistant, regardless of being virtual or not, and it is **available**, then the `cover` should not appear as `unknown`.
If you are currently facing any problem, please provide more details to understand whether this is a bug or not.
